package com.shop.Juliicasta.Model;

public class Account {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.FullName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.Phone
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.Email
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.Address
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.Username
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.Password
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.ROLE
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.Enable
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Boolean enable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.ID
	 * @return  the value of account.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.ID
	 * @param id  the value for account.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.FullName
	 * @return  the value of account.FullName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.FullName
	 * @param fullname  the value for account.FullName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.Phone
	 * @return  the value of account.Phone
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.Phone
	 * @param phone  the value for account.Phone
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.Email
	 * @return  the value of account.Email
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.Email
	 * @param email  the value for account.Email
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.Address
	 * @return  the value of account.Address
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.Address
	 * @param address  the value for account.Address
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.Username
	 * @return  the value of account.Username
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.Username
	 * @param username  the value for account.Username
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.Password
	 * @return  the value of account.Password
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.Password
	 * @param password  the value for account.Password
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.ROLE
	 * @return  the value of account.ROLE
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.ROLE
	 * @param role  the value for account.ROLE
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setRole(String role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.Enable
	 * @return  the value of account.Enable
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Boolean getEnable() {
		return enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.Enable
	 * @param enable  the value for account.Enable
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setEnable(Boolean enable) {
		this.enable = enable;
	}
}