package com.shop.Juliicasta.Model;

public class BillDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column billdetail.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column billdetail.BillID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer billid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column billdetail.ProductDetailID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer productdetailid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column billdetail.ProductName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String productname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column billdetail.SizeName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String sizename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column billdetail.ColorName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String colorname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column billdetail.Quantity
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column billdetail.Amount
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer amount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column billdetail.ID
	 * @return  the value of billdetail.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column billdetail.ID
	 * @param id  the value for billdetail.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column billdetail.BillID
	 * @return  the value of billdetail.BillID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getBillid() {
		return billid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column billdetail.BillID
	 * @param billid  the value for billdetail.BillID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setBillid(Integer billid) {
		this.billid = billid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column billdetail.ProductDetailID
	 * @return  the value of billdetail.ProductDetailID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getProductdetailid() {
		return productdetailid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column billdetail.ProductDetailID
	 * @param productdetailid  the value for billdetail.ProductDetailID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setProductdetailid(Integer productdetailid) {
		this.productdetailid = productdetailid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column billdetail.ProductName
	 * @return  the value of billdetail.ProductName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getProductname() {
		return productname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column billdetail.ProductName
	 * @param productname  the value for billdetail.ProductName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setProductname(String productname) {
		this.productname = productname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column billdetail.SizeName
	 * @return  the value of billdetail.SizeName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getSizename() {
		return sizename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column billdetail.SizeName
	 * @param sizename  the value for billdetail.SizeName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setSizename(String sizename) {
		this.sizename = sizename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column billdetail.ColorName
	 * @return  the value of billdetail.ColorName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getColorname() {
		return colorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column billdetail.ColorName
	 * @param colorname  the value for billdetail.ColorName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setColorname(String colorname) {
		this.colorname = colorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column billdetail.Quantity
	 * @return  the value of billdetail.Quantity
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column billdetail.Quantity
	 * @param quantity  the value for billdetail.Quantity
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column billdetail.Amount
	 * @return  the value of billdetail.Amount
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column billdetail.Amount
	 * @param amount  the value for billdetail.Amount
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}
}