package com.shop.Juliicasta.Model;

import java.util.ArrayList;
import java.util.List;

public class BillExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public BillExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andBillnoIsNull() {
			addCriterion("BillNo is null");
			return (Criteria) this;
		}

		public Criteria andBillnoIsNotNull() {
			addCriterion("BillNo is not null");
			return (Criteria) this;
		}

		public Criteria andBillnoEqualTo(String value) {
			addCriterion("BillNo =", value, "billno");
			return (Criteria) this;
		}

		public Criteria andBillnoNotEqualTo(String value) {
			addCriterion("BillNo <>", value, "billno");
			return (Criteria) this;
		}

		public Criteria andBillnoGreaterThan(String value) {
			addCriterion("BillNo >", value, "billno");
			return (Criteria) this;
		}

		public Criteria andBillnoGreaterThanOrEqualTo(String value) {
			addCriterion("BillNo >=", value, "billno");
			return (Criteria) this;
		}

		public Criteria andBillnoLessThan(String value) {
			addCriterion("BillNo <", value, "billno");
			return (Criteria) this;
		}

		public Criteria andBillnoLessThanOrEqualTo(String value) {
			addCriterion("BillNo <=", value, "billno");
			return (Criteria) this;
		}

		public Criteria andBillnoLike(String value) {
			addCriterion("BillNo like", value, "billno");
			return (Criteria) this;
		}

		public Criteria andBillnoNotLike(String value) {
			addCriterion("BillNo not like", value, "billno");
			return (Criteria) this;
		}

		public Criteria andBillnoIn(List<String> values) {
			addCriterion("BillNo in", values, "billno");
			return (Criteria) this;
		}

		public Criteria andBillnoNotIn(List<String> values) {
			addCriterion("BillNo not in", values, "billno");
			return (Criteria) this;
		}

		public Criteria andBillnoBetween(String value1, String value2) {
			addCriterion("BillNo between", value1, value2, "billno");
			return (Criteria) this;
		}

		public Criteria andBillnoNotBetween(String value1, String value2) {
			addCriterion("BillNo not between", value1, value2, "billno");
			return (Criteria) this;
		}

		public Criteria andAccountidIsNull() {
			addCriterion("AccountID is null");
			return (Criteria) this;
		}

		public Criteria andAccountidIsNotNull() {
			addCriterion("AccountID is not null");
			return (Criteria) this;
		}

		public Criteria andAccountidEqualTo(Integer value) {
			addCriterion("AccountID =", value, "accountid");
			return (Criteria) this;
		}

		public Criteria andAccountidNotEqualTo(Integer value) {
			addCriterion("AccountID <>", value, "accountid");
			return (Criteria) this;
		}

		public Criteria andAccountidGreaterThan(Integer value) {
			addCriterion("AccountID >", value, "accountid");
			return (Criteria) this;
		}

		public Criteria andAccountidGreaterThanOrEqualTo(Integer value) {
			addCriterion("AccountID >=", value, "accountid");
			return (Criteria) this;
		}

		public Criteria andAccountidLessThan(Integer value) {
			addCriterion("AccountID <", value, "accountid");
			return (Criteria) this;
		}

		public Criteria andAccountidLessThanOrEqualTo(Integer value) {
			addCriterion("AccountID <=", value, "accountid");
			return (Criteria) this;
		}

		public Criteria andAccountidIn(List<Integer> values) {
			addCriterion("AccountID in", values, "accountid");
			return (Criteria) this;
		}

		public Criteria andAccountidNotIn(List<Integer> values) {
			addCriterion("AccountID not in", values, "accountid");
			return (Criteria) this;
		}

		public Criteria andAccountidBetween(Integer value1, Integer value2) {
			addCriterion("AccountID between", value1, value2, "accountid");
			return (Criteria) this;
		}

		public Criteria andAccountidNotBetween(Integer value1, Integer value2) {
			addCriterion("AccountID not between", value1, value2, "accountid");
			return (Criteria) this;
		}

		public Criteria andEmployeeidIsNull() {
			addCriterion("EmployeeID is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeidIsNotNull() {
			addCriterion("EmployeeID is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeidEqualTo(Integer value) {
			addCriterion("EmployeeID =", value, "employeeid");
			return (Criteria) this;
		}

		public Criteria andEmployeeidNotEqualTo(Integer value) {
			addCriterion("EmployeeID <>", value, "employeeid");
			return (Criteria) this;
		}

		public Criteria andEmployeeidGreaterThan(Integer value) {
			addCriterion("EmployeeID >", value, "employeeid");
			return (Criteria) this;
		}

		public Criteria andEmployeeidGreaterThanOrEqualTo(Integer value) {
			addCriterion("EmployeeID >=", value, "employeeid");
			return (Criteria) this;
		}

		public Criteria andEmployeeidLessThan(Integer value) {
			addCriterion("EmployeeID <", value, "employeeid");
			return (Criteria) this;
		}

		public Criteria andEmployeeidLessThanOrEqualTo(Integer value) {
			addCriterion("EmployeeID <=", value, "employeeid");
			return (Criteria) this;
		}

		public Criteria andEmployeeidIn(List<Integer> values) {
			addCriterion("EmployeeID in", values, "employeeid");
			return (Criteria) this;
		}

		public Criteria andEmployeeidNotIn(List<Integer> values) {
			addCriterion("EmployeeID not in", values, "employeeid");
			return (Criteria) this;
		}

		public Criteria andEmployeeidBetween(Integer value1, Integer value2) {
			addCriterion("EmployeeID between", value1, value2, "employeeid");
			return (Criteria) this;
		}

		public Criteria andEmployeeidNotBetween(Integer value1, Integer value2) {
			addCriterion("EmployeeID not between", value1, value2, "employeeid");
			return (Criteria) this;
		}

		public Criteria andStatusidIsNull() {
			addCriterion("StatusID is null");
			return (Criteria) this;
		}

		public Criteria andStatusidIsNotNull() {
			addCriterion("StatusID is not null");
			return (Criteria) this;
		}

		public Criteria andStatusidEqualTo(Integer value) {
			addCriterion("StatusID =", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidNotEqualTo(Integer value) {
			addCriterion("StatusID <>", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidGreaterThan(Integer value) {
			addCriterion("StatusID >", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidGreaterThanOrEqualTo(Integer value) {
			addCriterion("StatusID >=", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidLessThan(Integer value) {
			addCriterion("StatusID <", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidLessThanOrEqualTo(Integer value) {
			addCriterion("StatusID <=", value, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidIn(List<Integer> values) {
			addCriterion("StatusID in", values, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidNotIn(List<Integer> values) {
			addCriterion("StatusID not in", values, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidBetween(Integer value1, Integer value2) {
			addCriterion("StatusID between", value1, value2, "statusid");
			return (Criteria) this;
		}

		public Criteria andStatusidNotBetween(Integer value1, Integer value2) {
			addCriterion("StatusID not between", value1, value2, "statusid");
			return (Criteria) this;
		}

		public Criteria andDatecreateIsNull() {
			addCriterion("DateCreate is null");
			return (Criteria) this;
		}

		public Criteria andDatecreateIsNotNull() {
			addCriterion("DateCreate is not null");
			return (Criteria) this;
		}

		public Criteria andDatecreateEqualTo(String value) {
			addCriterion("DateCreate =", value, "datecreate");
			return (Criteria) this;
		}

		public Criteria andDatecreateNotEqualTo(String value) {
			addCriterion("DateCreate <>", value, "datecreate");
			return (Criteria) this;
		}

		public Criteria andDatecreateGreaterThan(String value) {
			addCriterion("DateCreate >", value, "datecreate");
			return (Criteria) this;
		}

		public Criteria andDatecreateGreaterThanOrEqualTo(String value) {
			addCriterion("DateCreate >=", value, "datecreate");
			return (Criteria) this;
		}

		public Criteria andDatecreateLessThan(String value) {
			addCriterion("DateCreate <", value, "datecreate");
			return (Criteria) this;
		}

		public Criteria andDatecreateLessThanOrEqualTo(String value) {
			addCriterion("DateCreate <=", value, "datecreate");
			return (Criteria) this;
		}

		public Criteria andDatecreateLike(String value) {
			addCriterion("DateCreate like", value, "datecreate");
			return (Criteria) this;
		}

		public Criteria andDatecreateNotLike(String value) {
			addCriterion("DateCreate not like", value, "datecreate");
			return (Criteria) this;
		}

		public Criteria andDatecreateIn(List<String> values) {
			addCriterion("DateCreate in", values, "datecreate");
			return (Criteria) this;
		}

		public Criteria andDatecreateNotIn(List<String> values) {
			addCriterion("DateCreate not in", values, "datecreate");
			return (Criteria) this;
		}

		public Criteria andDatecreateBetween(String value1, String value2) {
			addCriterion("DateCreate between", value1, value2, "datecreate");
			return (Criteria) this;
		}

		public Criteria andDatecreateNotBetween(String value1, String value2) {
			addCriterion("DateCreate not between", value1, value2, "datecreate");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("Phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("Phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("Phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("Phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("Phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("Phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("Phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("Phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("Phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("Phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("Phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("Phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("Phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("Phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("Address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("Address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("Address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("Address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("Address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("Address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("Address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("Address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("Address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("Address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("Address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("Address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("Address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("Address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andStatusnameIsNull() {
			addCriterion("StatusName is null");
			return (Criteria) this;
		}

		public Criteria andStatusnameIsNotNull() {
			addCriterion("StatusName is not null");
			return (Criteria) this;
		}

		public Criteria andStatusnameEqualTo(String value) {
			addCriterion("StatusName =", value, "statusname");
			return (Criteria) this;
		}

		public Criteria andStatusnameNotEqualTo(String value) {
			addCriterion("StatusName <>", value, "statusname");
			return (Criteria) this;
		}

		public Criteria andStatusnameGreaterThan(String value) {
			addCriterion("StatusName >", value, "statusname");
			return (Criteria) this;
		}

		public Criteria andStatusnameGreaterThanOrEqualTo(String value) {
			addCriterion("StatusName >=", value, "statusname");
			return (Criteria) this;
		}

		public Criteria andStatusnameLessThan(String value) {
			addCriterion("StatusName <", value, "statusname");
			return (Criteria) this;
		}

		public Criteria andStatusnameLessThanOrEqualTo(String value) {
			addCriterion("StatusName <=", value, "statusname");
			return (Criteria) this;
		}

		public Criteria andStatusnameLike(String value) {
			addCriterion("StatusName like", value, "statusname");
			return (Criteria) this;
		}

		public Criteria andStatusnameNotLike(String value) {
			addCriterion("StatusName not like", value, "statusname");
			return (Criteria) this;
		}

		public Criteria andStatusnameIn(List<String> values) {
			addCriterion("StatusName in", values, "statusname");
			return (Criteria) this;
		}

		public Criteria andStatusnameNotIn(List<String> values) {
			addCriterion("StatusName not in", values, "statusname");
			return (Criteria) this;
		}

		public Criteria andStatusnameBetween(String value1, String value2) {
			addCriterion("StatusName between", value1, value2, "statusname");
			return (Criteria) this;
		}

		public Criteria andStatusnameNotBetween(String value1, String value2) {
			addCriterion("StatusName not between", value1, value2, "statusname");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bill
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 20 22:57:00 ICT 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}