package com.shop.Juliicasta.Model;

public class CartDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cartdetail.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cartdetail.CartID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer cartid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cartdetail.ProductDetailID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer productdetailid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cartdetail.Quantity
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cartdetail.ProductName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String productname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cartdetail.SizeName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String sizename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cartdetail.ColorName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String colorname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cartdetail.Price
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cartdetail.ImageName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String imagename;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartdetail.ID
	 * @return  the value of cartdetail.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartdetail.ID
	 * @param id  the value for cartdetail.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartdetail.CartID
	 * @return  the value of cartdetail.CartID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getCartid() {
		return cartid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartdetail.CartID
	 * @param cartid  the value for cartdetail.CartID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setCartid(Integer cartid) {
		this.cartid = cartid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartdetail.ProductDetailID
	 * @return  the value of cartdetail.ProductDetailID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getProductdetailid() {
		return productdetailid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartdetail.ProductDetailID
	 * @param productdetailid  the value for cartdetail.ProductDetailID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setProductdetailid(Integer productdetailid) {
		this.productdetailid = productdetailid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartdetail.Quantity
	 * @return  the value of cartdetail.Quantity
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartdetail.Quantity
	 * @param quantity  the value for cartdetail.Quantity
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartdetail.ProductName
	 * @return  the value of cartdetail.ProductName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getProductname() {
		return productname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartdetail.ProductName
	 * @param productname  the value for cartdetail.ProductName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setProductname(String productname) {
		this.productname = productname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartdetail.SizeName
	 * @return  the value of cartdetail.SizeName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getSizename() {
		return sizename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartdetail.SizeName
	 * @param sizename  the value for cartdetail.SizeName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setSizename(String sizename) {
		this.sizename = sizename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartdetail.ColorName
	 * @return  the value of cartdetail.ColorName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getColorname() {
		return colorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartdetail.ColorName
	 * @param colorname  the value for cartdetail.ColorName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setColorname(String colorname) {
		this.colorname = colorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartdetail.Price
	 * @return  the value of cartdetail.Price
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartdetail.Price
	 * @param price  the value for cartdetail.Price
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cartdetail.ImageName
	 * @return  the value of cartdetail.ImageName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getImagename() {
		return imagename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cartdetail.ImageName
	 * @param imagename  the value for cartdetail.ImageName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setImagename(String imagename) {
		this.imagename = imagename;
	}
}