package com.shop.Juliicasta.Model;

public class Cart {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cart.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cart.AccountID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer accountid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cart.ID
	 * @return  the value of cart.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cart.ID
	 * @param id  the value for cart.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cart.AccountID
	 * @return  the value of cart.AccountID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getAccountid() {
		return accountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cart.AccountID
	 * @param accountid  the value for cart.AccountID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setAccountid(Integer accountid) {
		this.accountid = accountid;
	}
}