package com.shop.Juliicasta.Model;

public class Color {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column color.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column color.Code
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column color.Name
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column color.ID
	 * @return  the value of color.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column color.ID
	 * @param id  the value for color.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column color.Code
	 * @return  the value of color.Code
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column color.Code
	 * @param code  the value for color.Code
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column color.Name
	 * @return  the value of color.Name
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column color.Name
	 * @param name  the value for color.Name
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setName(String name) {
		this.name = name;
	}
}