package com.shop.Juliicasta.Model;

import java.util.Date;

public class Comment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.AccountID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer accountid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.ProductID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer productid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.Content
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.DateCreate
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Date datecreate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.ID
	 * @return  the value of comment.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.ID
	 * @param id  the value for comment.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.AccountID
	 * @return  the value of comment.AccountID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getAccountid() {
		return accountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.AccountID
	 * @param accountid  the value for comment.AccountID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setAccountid(Integer accountid) {
		this.accountid = accountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.ProductID
	 * @return  the value of comment.ProductID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.ProductID
	 * @param productid  the value for comment.ProductID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.Content
	 * @return  the value of comment.Content
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.Content
	 * @param content  the value for comment.Content
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.DateCreate
	 * @return  the value of comment.DateCreate
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Date getDatecreate() {
		return datecreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.DateCreate
	 * @param datecreate  the value for comment.DateCreate
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setDatecreate(Date datecreate) {
		this.datecreate = datecreate;
	}
}