package com.shop.Juliicasta.Model;

public class Contact {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.FullName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.Phone
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.Type
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.Content
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.status
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Boolean status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.ID
	 * @return  the value of contact.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.ID
	 * @param id  the value for contact.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.FullName
	 * @return  the value of contact.FullName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.FullName
	 * @param fullname  the value for contact.FullName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.Phone
	 * @return  the value of contact.Phone
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.Phone
	 * @param phone  the value for contact.Phone
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.Type
	 * @return  the value of contact.Type
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.Type
	 * @param type  the value for contact.Type
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.Content
	 * @return  the value of contact.Content
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.Content
	 * @param content  the value for contact.Content
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.status
	 * @return  the value of contact.status
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.status
	 * @param status  the value for contact.status
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}
}