package com.shop.Juliicasta.Model;

public class Image {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image.ProductID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer productid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image.Name
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image.ID
	 * @return  the value of image.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image.ID
	 * @param id  the value for image.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image.ProductID
	 * @return  the value of image.ProductID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image.ProductID
	 * @param productid  the value for image.ProductID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image.Name
	 * @return  the value of image.Name
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image.Name
	 * @param name  the value for image.Name
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setName(String name) {
		this.name = name;
	}
}