package com.shop.Juliicasta.Model;

import java.util.Date;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.Code
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.Name
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.CategoryID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer categoryid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.Price
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.Detail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.DateImport
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Date dateimport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.MainImage
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String mainimage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.HaveSize
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Boolean havesize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.HaveColor
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Boolean havecolor;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.ID
	 * @return  the value of product.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.ID
	 * @param id  the value for product.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.Code
	 * @return  the value of product.Code
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.Code
	 * @param code  the value for product.Code
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.Name
	 * @return  the value of product.Name
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.Name
	 * @param name  the value for product.Name
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.CategoryID
	 * @return  the value of product.CategoryID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getCategoryid() {
		return categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.CategoryID
	 * @param categoryid  the value for product.CategoryID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.Price
	 * @return  the value of product.Price
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.Price
	 * @param price  the value for product.Price
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.Detail
	 * @return  the value of product.Detail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getDetail() {
		return detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.Detail
	 * @param detail  the value for product.Detail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.DateImport
	 * @return  the value of product.DateImport
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Date getDateimport() {
		return dateimport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.DateImport
	 * @param dateimport  the value for product.DateImport
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setDateimport(Date dateimport) {
		this.dateimport = dateimport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.MainImage
	 * @return  the value of product.MainImage
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getMainimage() {
		return mainimage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.MainImage
	 * @param mainimage  the value for product.MainImage
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setMainimage(String mainimage) {
		this.mainimage = mainimage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.HaveSize
	 * @return  the value of product.HaveSize
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Boolean getHavesize() {
		return havesize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.HaveSize
	 * @param havesize  the value for product.HaveSize
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setHavesize(Boolean havesize) {
		this.havesize = havesize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.HaveColor
	 * @return  the value of product.HaveColor
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Boolean getHavecolor() {
		return havecolor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.HaveColor
	 * @param havecolor  the value for product.HaveColor
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setHavecolor(Boolean havecolor) {
		this.havecolor = havecolor;
	}
}