package com.shop.Juliicasta.Model;

public class ProductDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productdetail.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productdetail.ProductID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer productid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productdetail.SizeID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer sizeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productdetail.ColorID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer colorid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productdetail.Quantity
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productdetail.SizeName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String sizename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column productdetail.ColorName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String colorname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productdetail.ID
	 * @return  the value of productdetail.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productdetail.ID
	 * @param id  the value for productdetail.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productdetail.ProductID
	 * @return  the value of productdetail.ProductID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productdetail.ProductID
	 * @param productid  the value for productdetail.ProductID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productdetail.SizeID
	 * @return  the value of productdetail.SizeID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getSizeid() {
		return sizeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productdetail.SizeID
	 * @param sizeid  the value for productdetail.SizeID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setSizeid(Integer sizeid) {
		this.sizeid = sizeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productdetail.ColorID
	 * @return  the value of productdetail.ColorID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getColorid() {
		return colorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productdetail.ColorID
	 * @param colorid  the value for productdetail.ColorID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setColorid(Integer colorid) {
		this.colorid = colorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productdetail.Quantity
	 * @return  the value of productdetail.Quantity
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productdetail.Quantity
	 * @param quantity  the value for productdetail.Quantity
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productdetail.SizeName
	 * @return  the value of productdetail.SizeName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getSizename() {
		return sizename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productdetail.SizeName
	 * @param sizename  the value for productdetail.SizeName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setSizename(String sizename) {
		this.sizename = sizename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column productdetail.ColorName
	 * @return  the value of productdetail.ColorName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getColorname() {
		return colorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column productdetail.ColorName
	 * @param colorname  the value for productdetail.ColorName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setColorname(String colorname) {
		this.colorname = colorname;
	}
}