package com.shop.Juliicasta.Model;

public class Slide {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column slide.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column slide.ImageName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	private String imagename;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column slide.ID
	 * @return  the value of slide.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column slide.ID
	 * @param id  the value for slide.ID
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column slide.ImageName
	 * @return  the value of slide.ImageName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public String getImagename() {
		return imagename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column slide.ImageName
	 * @param imagename  the value for slide.ImageName
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	public void setImagename(String imagename) {
		this.imagename = imagename;
	}
}