package com.shop.Juliicasta.Mapper;

import com.shop.Juliicasta.Model.BillDetail;
import com.shop.Juliicasta.Model.BillDetailExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BillDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billdetail
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	long countByExample(BillDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billdetail
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int deleteByExample(BillDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billdetail
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billdetail
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int insert(@Param("billid") int billid, @Param("productdetailid") int productdetailid, @Param("productname") String productname, @Param("sizename") String sizename, @Param("colorname") String colorname, @Param("quantity") int quantity, @Param("amount") int amount);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billdetail
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int insertSelective(BillDetail row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billdetail
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	List<BillDetail> selectByExample(BillDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billdetail
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	BillDetail selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billdetail
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") BillDetail row, @Param("example") BillDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billdetail
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int updateByExample(@Param("row") BillDetail row, @Param("example") BillDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billdetail
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int updateByPrimaryKeySelective(BillDetail row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table billdetail
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int updateByPrimaryKey(BillDetail row);
	
	List<BillDetail> selectByBillID(Integer id);
}