package com.shop.Juliicasta.Mapper;

import com.shop.Juliicasta.Model.Bill;
import com.shop.Juliicasta.Model.BillExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BillMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	long countByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int deleteByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int insert(@Param("billno") String billno, @Param("accountid") int accountid, @Param("statusid") int statusid, @Param("datecreate") String datecreate, @Param("phone") String phone, @Param("address") String address, @Param("statusname") String statusname);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int insertSelective(Bill row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	List<Bill> selectByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	Bill selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Bill row, @Param("example") BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int updateByExample(@Param("row") Bill row, @Param("example") BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int updateByPrimaryKeySelective(Bill row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int updateByPrimaryKey(Bill row);
	
	Bill selectNewBillForAccount(int accId);
	
	List<Bill> selectListBillForAccount(int accId);
	
	List<Bill> selectAllBillForAccount(int accId);
	
	int cancelBill(int id);
	
	List<Bill> selectNewListBill();
	
	int updateBill(@Param("statusid") int statusid, @Param("statusname") String statusname, @Param("id") int id);
	
	int updateBillAndEmp(@Param("statusid") int statusid, @Param("statusname") String statusname, @Param("employeeid") int employeeid, @Param("id") int id);
}