package com.shop.Juliicasta.Mapper;

import com.shop.Juliicasta.Model.Cart;
import com.shop.Juliicasta.Model.CartExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CartMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	long countByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int deleteByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int insert(int accId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int insertSelective(Cart row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	List<Cart> selectByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	Cart selectByPrimaryKey(Integer id);
	
	Cart selectByAccount(Integer accId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Cart row, @Param("example") CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int updateByExample(@Param("row") Cart row, @Param("example") CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int updateByPrimaryKeySelective(Cart row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int updateByPrimaryKey(Cart row);
}