package com.shop.Juliicasta.Mapper;

import com.shop.Juliicasta.Model.CartDetail;
import com.shop.Juliicasta.Model.CartDetailExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CartDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cartdetail
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	long countByExample(CartDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cartdetail
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int deleteByExample(CartDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cartdetail
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cartdetail
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cartdetail
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int insertSelective(CartDetail row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cartdetail
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	List<CartDetail> selectByExample(CartDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cartdetail
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	CartDetail selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cartdetail
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") CartDetail row, @Param("example") CartDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cartdetail
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int updateByExample(@Param("row") CartDetail row, @Param("example") CartDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cartdetail
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int updateByPrimaryKeySelective(CartDetail row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cartdetail
	 * @mbg.generated  Wed May 18 11:02:10 ICT 2022
	 */
	int updateByPrimaryKey(CartDetail row);
	
	List<CartDetail> selectByCartId(@Param("cartid") int cartid);
	
	int insert(@Param("cartid") int cartid, @Param("productdetailid") int productdetailid, @Param("quantity") int quantity, @Param("productname") String productname, @Param("sizename") String sizename, @Param("colorname") String colorname, @Param("price") int price, @Param("imagename") String imagename);
	
	int addQuantity(@Param("quantity") int quantity, @Param("price") int price, @Param("id") int id);
	
	CartDetail selectItem(@Param("cartid") int cartid, @Param("productdetailid") int productdetailid);
	
	int deleteByCartID(Integer id);
}