package com.shop.Juliicasta.Mapper;

import com.shop.Juliicasta.Model.Color;
import com.shop.Juliicasta.Model.ColorExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ColorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table color
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	long countByExample(ColorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table color
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int deleteByExample(ColorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table color
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table color
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int insert(Color row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table color
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int insertSelective(Color row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table color
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	List<Color> selectByExample(ColorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table color
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	Color selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table color
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Color row, @Param("example") ColorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table color
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int updateByExample(@Param("row") Color row, @Param("example") ColorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table color
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int updateByPrimaryKeySelective(Color row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table color
	 * @mbg.generated  Wed May 25 10:27:15 ICT 2022
	 */
	int updateByPrimaryKey(Color row);

	Color selectByID(Integer id);
}