package com.shop.Juliicasta.Mapper;

import com.shop.Juliicasta.Model.Contact;
import com.shop.Juliicasta.Model.ContactExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Thu Jun 09 22:33:06 ICT 2022
     */
    long countByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Thu Jun 09 22:33:06 ICT 2022
     */
    int deleteByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Thu Jun 09 22:33:06 ICT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Thu Jun 09 22:33:06 ICT 2022
     */
    int insert(Contact row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Thu Jun 09 22:33:06 ICT 2022
     */
    int insertSelective(Contact row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Thu Jun 09 22:33:06 ICT 2022
     */
    List<Contact> selectByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Thu Jun 09 22:33:06 ICT 2022
     */
    Contact selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Thu Jun 09 22:33:06 ICT 2022
     */
    int updateByExampleSelective(@Param("row") Contact row, @Param("example") ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Thu Jun 09 22:33:06 ICT 2022
     */
    int updateByExample(@Param("row") Contact row, @Param("example") ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Thu Jun 09 22:33:06 ICT 2022
     */
    int updateByPrimaryKeySelective(Contact row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Thu Jun 09 22:33:06 ICT 2022
     */
    int updateByPrimaryKey(Contact row);
    
    int editContactStatus(@Param("num") int num, @Param("id") int id);
}