package com.shop.Juliicasta.Mapper;

import com.shop.Juliicasta.Model.Image;
import com.shop.Juliicasta.Model.ImageExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ImageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	long countByExample(ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int deleteByExample(ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int insert(Image row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int insertSelective(Image row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	List<Image> selectByExample(ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	Image selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Image row, @Param("example") ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByExample(@Param("row") Image row, @Param("example") ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByPrimaryKeySelective(Image row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByPrimaryKey(Image row);

	Image selectByName(@Param("name") String name);

	List<Image> selectByProductID(Integer productID);
}