package com.shop.Juliicasta.Mapper;

import com.shop.Juliicasta.Model.Product;
import com.shop.Juliicasta.Model.ProductExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	long countByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int deleteByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int insert(Product row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int insertSelective(Product row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	List<Product> selectByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	Product selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Product row, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByExample(@Param("row") Product row, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByPrimaryKeySelective(Product row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByPrimaryKey(Product row);

	int countByCate(int cate);
	
	int countByName(String name);
	
	int countByPrice(@Param("x") int x, @Param("y") int y);
	
	int countByCateAndName(@Param("cate") int cate, @Param("name") String name);
	
	int countByCateAndPrice(@Param("cate") int cate, @Param("x") int x, @Param("y") int y);
	
	List<Product> selectAllProduct(Integer start);
	
	List<Product> selectAllProductByCateForProductDetail(int cate);
	
	List<Product> selectAllProductByCate(@Param("cate") int cate, @Param("start") int start);
	
	List<Product> selectTop(int num);
	
	List<Product> selectPriceInc(@Param("start") int start);
	
	List<Product> selectPriceDec(@Param("start") int start);
	
	List<Product> selectDateNew(@Param("start") int start);
	
	List<Product> selectDateOld(@Param("start") int start);
	
	List<Product> selectByCateAndSortByPriceInc(@Param("cate") int cate, @Param("start") int start);
	
	List<Product> selectByCateAndSortByPriceDec(@Param("cate") int cate, @Param("start") int start);
	
	List<Product> selectByCateAndSortByNew(@Param("cate") int cate, @Param("start") int start);
	
	List<Product> selectByCateAndSortByOld(@Param("cate") int cate, @Param("start") int start);
	
	List<Product> selectByCateAndName(@Param("cate") int cate, @Param("name") String name, @Param("start") int start);
	
	List<Product> selectByName(@Param("name") String name, @Param("start") int start);
	
	List<Product> selectByPrice(@Param("x") int x, @Param("y") int y, @Param("start") int start);
	
	List<Product> selectByCateAndPrice(@Param("cate") int cate ,@Param("x") int x, @Param("y") int y, @Param("start") int start);

	List<Product> selectAllProductForAdmin();
	
	List<Product> selectProductByCateForAdmin(int cate);
}