package com.shop.Juliicasta.Mapper;

import com.shop.Juliicasta.Model.ProductDetail;
import com.shop.Juliicasta.Model.ProductDetailExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProductDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productdetail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	long countByExample(ProductDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productdetail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	int deleteByExample(ProductDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productdetail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productdetail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	int insert(ProductDetail row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productdetail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	int insertSelective(ProductDetail row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productdetail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	List<ProductDetail> selectByExample(ProductDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productdetail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	ProductDetail selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productdetail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") ProductDetail row, @Param("example") ProductDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productdetail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	int updateByExample(@Param("row") ProductDetail row, @Param("example") ProductDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productdetail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	int updateByPrimaryKeySelective(ProductDetail row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productdetail
	 * @mbg.generated  Wed Jul 06 20:47:06 ICT 2022
	 */
	int updateByPrimaryKey(ProductDetail row);

	List<ProductDetail> selectByProductID(int id);

	ProductDetail selectProductDetail(@Param("proId") int proId, @Param("sizeId") int sizeId, @Param("colorId") int colorId);

	int updateQuantity(@Param("quantity") int quantity, @Param("id") int id);
}