package com.shop.Juliicasta.Mapper;

import com.shop.Juliicasta.Model.Size;
import com.shop.Juliicasta.Model.SizeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SizeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table size
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	long countByExample(SizeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table size
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int deleteByExample(SizeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table size
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table size
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int insert(Size row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table size
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int insertSelective(Size row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table size
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	List<Size> selectByExample(SizeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table size
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	Size selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table size
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Size row, @Param("example") SizeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table size
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByExample(@Param("row") Size row, @Param("example") SizeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table size
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByPrimaryKeySelective(Size row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table size
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByPrimaryKey(Size row);

	Size selectByID(Integer id);
}