package com.shop.Juliicasta.Mapper;

import com.shop.Juliicasta.Model.Slide;
import com.shop.Juliicasta.Model.SlideExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SlideMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slide
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	long countByExample(SlideExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slide
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int deleteByExample(SlideExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slide
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slide
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int insert(Slide row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slide
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int insertSelective(Slide row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slide
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	List<Slide> selectByExample(SlideExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slide
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	Slide selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slide
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Slide row, @Param("example") SlideExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slide
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByExample(@Param("row") Slide row, @Param("example") SlideExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slide
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByPrimaryKeySelective(Slide row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table slide
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByPrimaryKey(@Param("imagename") String imagename, @Param("id") int id);
}