package com.shop.Juliicasta.Mapper;

import com.shop.Juliicasta.Model.Status;
import com.shop.Juliicasta.Model.StatusExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface StatusMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table status
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	long countByExample(StatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table status
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int deleteByExample(StatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table status
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table status
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int insert(Status row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table status
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int insertSelective(Status row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table status
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	List<Status> selectByExample(StatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table status
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	Status selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table status
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Status row, @Param("example") StatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table status
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByExample(@Param("row") Status row, @Param("example") StatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table status
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByPrimaryKeySelective(Status row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table status
	 * @mbg.generated  Wed May 18 11:00:35 ICT 2022
	 */
	int updateByPrimaryKey(Status row);
}